### PR TITLE
#13 - removing invalid cert due to non-https link for issuer profile

### PR DESCRIPTION
**Pull request by ghost**
Non-https link redirecting to an https link with `:80` appended to the base url is causing it to fail.

### CODE REVIEW

**Review by raiseandfall — APPROVED** [review]
LGTM

**Comment by lemoustachiste** [comment]
do you want to maybe replace it?
This one is a valid and working V1: https://raw.githubusercontent.com/learningmachine/blockcerts-universal-verifier/master/test/fixtures/valid-v1-certificate.json?token=AMNICsAJVez3nHNABRVzDYM5fqR1_o9sks5bcurMwA%3D%3D

**Comment by ghost** [comment]
@lemoustachiste replaced

**Review by lemoustachiste — APPROVED** [review]
nice!

**Pull request merged**
